"""Markdown test report generator."""

from datetime import datetime, timezone
from pathlib import Path

from video_qa import __version__
from video_qa.config import AnalysisConfig
from video_qa.core.clusterer import Region
from video_qa.core.extractor import VideoMetadata


def generate_report(
    metadata: VideoMetadata,
    regions: list[Region],
    config: AnalysisConfig,
    image_dir: Path,
) -> str:
    """Generate a Markdown test report."""
    lines: list[str] = []

    # Header
    lines.append(f"# Video QA Report: {metadata.file_path.name}")
    lines.append("")
    lines.append("## Video Info")
    lines.append("")
    lines.append("| Property | Value |")
    lines.append("|----------|-------|")
    lines.append(f"| File | `{metadata.file_path.name}` |")
    lines.append(f"| Resolution | {metadata.width}x{metadata.height} |")
    lines.append(f"| Duration | {metadata.duration:.1f}s |")
    lines.append(f"| Original FPS | {metadata.fps:.1f} |")
    lines.append(f"| Analysis FPS | {config.fps} |")
    lines.append(f"| RMSE Threshold | {config.threshold} |")
    lines.append(f"| Cluster Window | {config.cluster_window}s |")
    lines.append("")

    # Summary
    lines.append("## Summary")
    lines.append("")
    total_change_time = sum(r.timestamp_end - r.timestamp_start for r in regions)
    lines.append(f"- **Regions detected**: {len(regions)}")
    lines.append(f"- **Total change time**: {total_change_time:.1f}s")
    if regions:
        max_rmse = max(r.max_rmse for r in regions)
        lines.append(f"- **Max RMSE**: {max_rmse:.4f}")
    lines.append("")

    # Regions
    if regions:
        lines.append("## Detected Regions")
        lines.append("")

        for i, region in enumerate(regions, 1):
            lines.append(f"### Region {i}")
            lines.append("")
            lines.append("| Property | Value |")
            lines.append("|----------|-------|")
            lines.append(
                f"| Time | "
                f"{region.timestamp_start:.1f}s - "
                f"{region.timestamp_end:.1f}s |"
            )
            lines.append(f"| Max RMSE | {region.max_rmse:.4f} |")
            lines.append(f"| Frames | " f"{region.start_index} - {region.end_index} |")
            lines.append("")

            # Timeline image reference
            rel_path = f"images/region_{i:02d}.png"
            lines.append(f"![Region {i} Timeline]({rel_path})")
            lines.append("")
    else:
        lines.append("## Result")
        lines.append("")
        lines.append("No significant changes detected.")
        lines.append("")

    # Footer
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    lines.append("---")
    lines.append("")
    lines.append(
        f"Generated by [video-qa](https://github.com/"
        f"miyashita337/video-qa) v{__version__} at {now}"
    )

    return "\n".join(lines) + "\n"
